production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: 	<%= ENV["TWITTER_API_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_API_SECRET"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  google_api_secret: <%= ENV["GOOGLE_API_SECRET"] %>
  linkedin_api_key: <%= ENV["LINKEDIN_API_KEY"] %>
  linkedin_api_secret: <%= ENV["LINKEDIN_API_SECRET"] %>
  instagram_api_key: <%= ENV["INSTAGRAM_API_KEY"] %>
  instagram_api_secret: <%= ENV["INSTAGRAM_API_SECRET"] %>
  facebook_api_key: <%= ENV["FACEBOOK_API_KEY"] %>
  facebook_api_secret: <%= ENV["FACEBOOK_API_SECRET"] %>
