# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4bdbbff7ee22515aadd00843e13b0382f4145ef53abe5588c2d01b191ab3b1f2ee02590ded867252f1cdcf4062baa156140ec9b3dd2cd0c37a3dce11d44a927
  twitter_api_key: 	yYEfBscmO1unXoXs1oi37YsvE
  twitter_api_secret: zImF1T4qcyO9wsXqbR2IAhwwXTj6vn1ViSrOAcQOkSJjVSWmAV
  google_api_key: 933125985556-iclva98anmruta6khl5c6rtfiamilfmr.apps.googleusercontent.com
  google_api_secret: 9j8G4CxRaZYdySl49tOAWwbH
  linkedin_api_key: 759etv8zt1nuvx
  linkedin_api_secret: lNJfbqbBCjTL8qIf
  instagram_api_key: e3c7ca99653546de9b4b57484cf13cb9
  instagram_api_secret: d6353d34513548da802b81c4d0be9204
  facebook_api_key: 224193301260178
  facebook_api_secret: a925d5bfa7476d14eb5db820f9e039fd


test:
  secret_key_base: d59327a935e61a5e98973bab1c507a0d7ff7361d14565f71edf59ee08cda686d284bee94131dd4fb708caf44cce5741ea9fe13753b132c57a89b5bf559fabc95
  twitter_api_key: 	yYEfBscmO1unXoXs1oi37YsvE
  twitter_api_secret: zImF1T4qcyO9wsXqbR2IAhwwXTj6vn1ViSrOAcQOkSJjVSWmAV
  google_api_key: 933125985556-iclva98anmruta6khl5c6rtfiamilfmr.apps.googleusercontent.com
  google_api_secret: 9j8G4CxRaZYdySl49tOAWwbH
  linkedin_api_key: 759etv8zt1nuvx
  linkedin_api_secret: lNJfbqbBCjTL8qIf
  instagram_api_key: e3c7ca99653546de9b4b57484cf13cb9
  instagram_api_secret: d6353d34513548da802b81c4d0be9204
  facebook_api_key: 224193301260178
  facebook_api_secret: a925d5bfa7476d14eb5db820f9e039fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
